document.addEventListener('DOMContentLoaded', () => {
  if (document.body.dataset.page !== 'home') return;
  const today = getLocalDateString(); const entries = getJournals().sort((a, b) => b.date.localeCompare(a.date));
  byId('greeting').innerHTML = `${getGreeting()}, Dipanshu <span>👋</span>`;
  byId('dateLabel').textContent = new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date()).toUpperCase();
  const todayEntry = entries.find(entry => entry.date === today);
  const todayCard = byId('todayCard');
  if (todayEntry) { todayCard.innerHTML = `<div class="today-info"><p class="eyebrow">TODAY'S JOURNAL</p><h2>${escapeHtml(todayEntry.title || 'A page from today')}</h2><div class="today-date">${formatDate(today)}</div><div class="today-mood"><span class="mood-emoji">${todayEntry.mood.emoji}</span>${todayEntry.mood.label}</div><p class="today-preview">${escapeHtml(truncateText(todayEntry.content, 125))}</p></div><div class="today-actions"><a class="button button-primary" href="pages/journal.html?id=${encodeURIComponent(todayEntry.id)}">Read today's entry <span>→</span></a><a class="quiet-link" href="pages/add-journal.html?id=${encodeURIComponent(todayEntry.id)}">Edit entry</a></div>`; }
  else { todayCard.innerHTML = `<div class="today-info"><p class="eyebrow">TODAY'S JOURNAL</p><h2>A blank page awaits.</h2><div class="today-date">${formatDate(today)}</div><div class="today-mood"><span class="mood-emoji">✦</span>How are you feeling?</div></div><div class="today-actions"><a class="button button-primary" href="pages/add-journal.html">Write today's entry <span>→</span></a><span class="subtle">A few lines are enough.</span></div>`; }
  const monthPrefix = today.slice(0, 7); const stats = [{ icon: '◌', value: entries.length, label: 'Total entries' }, { icon: '◷', value: entries.filter(entry => entry.date.startsWith(monthPrefix)).length, label: 'This month' }, { icon: '↗', value: `${calculateStreak(entries)} days`, label: 'Current streak' }, { icon: entries[0]?.mood.emoji || '—', value: entries.length ? mostCommonMood(entries).label : '—', label: 'Most common mood' }];
  byId('statsGrid').innerHTML = stats.map(stat => `<article class="stat-card"><div class="stat-icon">${stat.icon}</div><h3>${stat.value}</h3><p>${stat.label}</p></article>`).join('');
  const recent = byId('recentList');
  recent.innerHTML = entries.slice(0, 4).map(entry => `<article class="recent-item" data-id="${entry.id}"><div class="mood-bubble">${entry.mood.emoji}</div><div class="recent-copy"><h3>${escapeHtml(entry.title || 'Untitled reflection')}</h3><p>${escapeHtml(truncateText(entry.content))}</p></div><time class="recent-date">${formatShortDate(entry.date)}</time></article>`).join('') || `<div class="empty-state"><div class="empty-icon">✦</div><h2>Your journal is quiet.</h2><p>Begin with one small observation from today.</p><a class="button button-primary" href="pages/add-journal.html">Write your first entry</a></div>`;
  recent.querySelectorAll('[data-id]').forEach(item => item.addEventListener('click', () => { window.location.href = `pages/journal.html?id=${encodeURIComponent(item.dataset.id)}`; }));
  const moodCounts = {}; entries.forEach(entry => { moodCounts[entry.mood.id] = (moodCounts[entry.mood.id] || 0) + 1; }); const max = Math.max(...Object.values(moodCounts), 1);
  byId('moodSummary').innerHTML = entries.length ? Object.entries(moodCounts).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([id, count]) => { const mood = getMood(id); return `<div class="mood-line"><span class="emoji">${mood.emoji}</span><span class="label">${mood.label}</span><span class="mood-bar"><span style="width:${(count / max) * 100}%"></span></span><span class="count">${count}</span></div>`; }).join('') : '<p class="subtle">Your mood patterns will appear here.</p>';
});
function mostCommonMood(entries) { const counts = {}; entries.forEach(entry => { counts[entry.mood.id] = (counts[entry.mood.id] || 0) + 1; }); return getMood(Object.entries(counts).sort((a, b) => b[1] - a[1])[0][0]); }
function calculateStreak(entries) { const dates = new Set(entries.map(entry => entry.date)); let cursor = new Date(); if (!dates.has(getLocalDateString(cursor))) cursor.setDate(cursor.getDate() - 1); let streak = 0; while (dates.has(getLocalDateString(cursor))) { streak++; cursor.setDate(cursor.getDate() - 1); } return streak; }
