document.addEventListener('DOMContentLoaded', () => {
  const page = document.body.dataset.page;
  if (page === 'journal') initJournalList();
  if (page === 'add') initJournalForm();
});

function initJournalList() {
  const search = byId('searchInput'); const dateFilter = byId('dateFilter'); const moodFilter = byId('moodFilter'); const results = byId('journalResults');
  MOODS.forEach(mood => { const option = document.createElement('option'); option.value = mood.id; option.textContent = `${mood.emoji} ${mood.label}`; moodFilter.appendChild(option); });
  function render() { const query = search.value.trim().toLowerCase(); const date = dateFilter.value; const mood = moodFilter.value; let entries = getJournals().sort((a, b) => b.date.localeCompare(a.date)); const today = parseDate(getLocalDateString()); entries = entries.filter(entry => { const entryDate = parseDate(entry.date); const matchesQuery = !query || [entry.title, entry.content, entry.mood.label, entry.date].some(value => value?.toLowerCase().includes(query)); const daysAgo = Math.floor((today - entryDate) / 86400000); const matchesDate = date === 'all' || (date === 'today' && entry.date === getLocalDateString()) || (date === 'week' && daysAgo >= 0 && daysAgo < 7) || (date === 'month' && entry.date.startsWith(getLocalDateString().slice(0, 7))) || (date === 'year' && entry.date.startsWith(getLocalDateString().slice(0, 4))); return matchesQuery && matchesDate && (mood === 'all' || entry.mood.id === mood); }); byId('entryCount').textContent = `${entries.length} ${entries.length === 1 ? 'entry' : 'entries'}`; results.innerHTML = entries.length ? entries.map(entry => journalCardMarkup(entry)).join('') : `<div class="empty-state"><div class="empty-icon">${query || date !== 'all' || mood !== 'all' ? '⌕' : '✦'}</div><h2>${query || date !== 'all' || mood !== 'all' ? 'No entries found' : 'Your journal is empty'}</h2><p>${query || date !== 'all' || mood !== 'all' ? 'Try changing your search or filters.' : 'Start capturing your thoughts, feelings and memories today.'}</p>${query || date !== 'all' || mood !== 'all' ? '' : '<a class="button button-primary" href="add-journal.html">Write your first entry</a>'}</div>`; results.querySelectorAll('[data-view]').forEach(card => card.addEventListener('click', event => { if (!event.target.closest('button')) openDetail(card.dataset.view); })); results.querySelectorAll('[data-edit]').forEach(button => button.addEventListener('click', () => { window.location.href = `add-journal.html?id=${encodeURIComponent(button.dataset.edit)}`; })); results.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click', () => askDelete(button.dataset.delete))); }
  [search, dateFilter, moodFilter].forEach(control => control.addEventListener('input', render)); byId('clearFilters').addEventListener('click', () => { search.value = ''; dateFilter.value = 'all'; moodFilter.value = 'all'; render(); }); byId('clearAllButton').addEventListener('click', () => { byId('confirmTitle').textContent = 'Delete all journals?'; byId('confirmMessage').textContent = 'This will permanently remove all journal entries from this browser.'; byId('confirmAction').textContent = 'Delete everything'; byId('confirmAction').onclick = () => { clearAllJournals(); closeModal('confirmModal'); showToast('All journals have been deleted.', 'success'); render(); }; openModal('confirmModal'); });
  const id = new URLSearchParams(window.location.search).get('id'); render(); if (id) openDetail(id);
}
function journalCardMarkup(entry) { return `<article class="journal-card" data-view="${entry.id}"><div class="journal-card-top"><div class="journal-mood"><span>${entry.mood.emoji}</span>${entry.mood.label}</div><time class="journal-date">${formatShortDate(entry.date)}</time></div><h3>${escapeHtml(entry.title || 'Untitled reflection')}</h3><p class="preview">${escapeHtml(truncateText(entry.content, 145))}</p><div class="card-actions"><button type="button" data-edit="${entry.id}">Edit</button><button type="button" data-delete="${entry.id}">Delete</button><span class="quiet-link">Read →</span></div></article>`; }
function openDetail(id) { const entry = getJournalById(id); if (!entry) return; byId('detailBody').innerHTML = `<div class="detail-mood"><span>${entry.mood.emoji}</span>${entry.mood.label}</div><h2 class="detail-title" id="detailTitle">${escapeHtml(entry.title || 'Untitled reflection')}</h2><div class="detail-date">${formatDate(entry.date)}</div><div class="detail-content">${escapeHtml(entry.content)}</div><div class="modal-actions"><button class="button button-ghost" data-close-modal type="button">Close</button><a class="button button-primary" href="add-journal.html?id=${encodeURIComponent(entry.id)}">Edit entry <span>→</span></a></div>`; byId('detailBody').querySelector('[data-close-modal]').addEventListener('click', () => closeModal('detailModal')); openModal('detailModal'); }
function askDelete(id) { byId('confirmTitle').textContent = 'Delete journal?'; byId('confirmMessage').textContent = 'Are you sure you want to delete this journal? This action cannot be undone.'; byId('confirmAction').textContent = 'Delete'; byId('confirmAction').onclick = () => { deleteJournal(id); closeModal('confirmModal'); closeModal('detailModal'); showToast('Journal deleted.', 'success'); window.history.replaceState({}, '', window.location.pathname); document.querySelector('[data-page="journal"]') && location.reload(); }; openModal('confirmModal'); }

function initJournalForm() {
  const form = byId('journalForm'); const editId = new URLSearchParams(window.location.search).get('id'); const existing = editId ? getJournalById(editId) : null; let selectedMood = existing?.mood.id || null; let duplicateEntry = null;
  byId('entryDate').value = existing?.date || getLocalDateString(); if (existing) { byId('formEyebrow').textContent = 'CONTINUE A THOUGHT'; byId('formHeading').textContent = 'Edit your entry'; byId('entryTitle').value = existing.title || ''; byId('entryContent').value = existing.content; byId('saveButton').innerHTML = 'Update entry <span>→</span>'; }
  byId('moodPicker').innerHTML = MOODS.map(mood => `<button type="button" class="mood-option ${selectedMood === mood.id ? 'selected' : ''}" data-mood="${mood.id}"><span class="emoji">${mood.emoji}</span><span class="mood-label">${mood.label}</span></button>`).join(''); byId('moodPicker').querySelectorAll('[data-mood]').forEach(button => button.addEventListener('click', () => { selectedMood = button.dataset.mood; byId('moodPicker').querySelectorAll('.mood-option').forEach(option => option.classList.toggle('selected', option === button)); byId('moodError').textContent = ''; }));
  const title = byId('entryTitle'); const content = byId('entryContent'); const updateCounter = () => { byId('titleCounter').textContent = `${title.value.length} / 100`; byId('contentCounter').textContent = `${content.value.length} / 5000`; }; title.addEventListener('input', updateCounter); content.addEventListener('input', updateCounter); updateCounter();
  form.addEventListener('submit', event => { event.preventDefault(); clearErrors(); const valid = validateForm(selectedMood); if (!valid) return; const date = byId('entryDate').value; duplicateEntry = getJournals().find(entry => entry.date === date && entry.id !== editId); if (duplicateEntry) { byId('editExisting').onclick = () => { window.location.href = `add-journal.html?id=${encodeURIComponent(duplicateEntry.id)}`; }; openModal('duplicateModal'); return; } const mood = getMood(selectedMood); const journal = { id: editId || generateId(), date, title: title.value.trim(), content: content.value.trim(), mood, createdAt: existing?.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; const saved = existing ? updateJournal(editId, journal) : saveJournal(journal); if (!saved) { showToast('Unable to save in this browser. Check storage settings.', 'error'); return; } showToast(existing ? 'Journal updated successfully.' : 'Journal saved successfully.', 'success'); setTimeout(() => { window.location.href = 'journal.html'; }, 550); });
}
function clearErrors() { document.querySelectorAll('.field-error').forEach(error => { error.textContent = ''; }); document.querySelectorAll('.has-error').forEach(field => field.classList.remove('has-error')); }
function validateForm(selectedMood) { let valid = true; const date = byId('entryDate'); const title = byId('entryTitle'); const content = byId('entryContent'); const fail = (input, error, message) => { error.textContent = message; input.closest('.field')?.classList.add('has-error'); valid = false; }; if (!date.value) fail(date, byId('dateError'), 'Please choose a date.'); if (title.value.length > 100) fail(title, byId('titleError'), 'Title must be 100 characters or fewer.'); if (content.value.trim().length < 10) fail(content, byId('contentError'), content.value.trim() ? 'Journal content must be at least 10 characters.' : 'Please write something in your journal.'); if (content.value.length > 5000) fail(content, byId('contentError'), 'Journal content must be 5000 characters or fewer.'); if (!selectedMood) { byId('moodError').textContent = 'Please select your mood.'; valid = false; } if (!valid) document.querySelector('.field-error:not(:empty)')?.closest('.field')?.querySelector('input,textarea')?.focus(); return valid; }
